<a href="https://colab.research.google.com/github/GaryPython/-Machine-Learning/blob/main/%E9%9D%9E%E7%9B%A3%E7%9D%A3%E5%AD%B8%E7%BF%92/13_%E9%9A%B1%E5%90%AB%E7%8B%84%E5%88%A9%E5%85%8B%E9%9B%B7%E5%88%86%E4%BD%88%EF%BC%88Latent_Dirichlet_Alloocation%EF%BC%8CLDA%EF%BC%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 隱含狄利克雷分佈（Latent Dirichlet Alloocation，LDA）



*   降維
>建立文件模型
>
>處理自然語言

步驟：


1.   隨機賦予個文件裡的詞彙一個主題
2.   依據分配給詞彙的主題，算出各文件的「主題機率」
3.   依據分配給詞彙的主題，算出各主題的「詞彙機率」
4.   根據2. 和 3.相乘後的機率，再度賦予「各文件的詞彙主題」
5.   重複 2. 3. 4. ，直到滿足收斂條件




補充：
  
[LDA主题－20newsgroups](https://blog.csdn.net/TiffanyRabbit/article/details/76445909)

In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
 

# remove文本以外的資訊
data = fetch_20newsgroups(remove=('headers', 'footers', 'quotes'))
max_features = 1000
# 文字資料轉換為向量
tf_vectorizer = CountVectorizer(max_features=max_features,
stop_words='english')
tf = tf_vectorizer.fit_transform(data.data)
#20個主題
n_topics = 20
model = LatentDirichletAllocation(n_components=n_topics)
model.fit(tf)
print(model.components_) # 各主題詞彙分佈
#print(model.transform(tf)) #以主題呈現的文件

Downloading 20news dataset. This may take a few minutes.
Downloading dataset from https://ndownloader.figshare.com/files/5975967 (14 MB)

[[5.00007172e-02 5.00013526e-02 5.00000003e-02 ... 5.00000008e-02
  1.94336567e+01 5.00000005e-02]
 [1.44812386e+00 2.77120530e+00 1.37438336e+01 ... 5.00000025e-02
  1.01704268e+01 7.57994402e+00]
 [5.00000005e-02 4.46473990e+01 3.64398397e+00 ... 5.00000007e-02
  3.98355469e+00 6.11327205e-01]
 ...
 [5.00000000e-02 5.00000000e-02 5.00000000e-02 ... 5.00000000e-02
  5.00000000e-02 5.00000000e-02]
 [3.92138919e+00 2.56775060e+01 5.00000000e-02 ... 9.94902826e+01
  1.01837987e+01 5.00000010e-02]
 [5.00000002e-02 3.74766322e+01 5.00000003e-02 ... 1.62939603e+02
  5.00000477e-02 4.49772052e+01]]

##CountVectorizer - tf

In [ ]:
tf

<11314x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 286250 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
data = fetch_20newsgroups(remove=('headers', 'footers', 'quotes'))
max_features = 1000
tf_vectorizer = CountVectorizer(max_features=max_features,stop_words='english')
tf = tf_vectorizer.fit_transform(data.data)
r = pd.DataFrame(tf.toarray(),columns=tf_vectorizer.get_feature_names())

print("CountVector")
r

CountVector

       00  000  01  02  03  04  0d  ...  x11  xt  year  years  yes  york  young
0       0    0   0   0   0   0   0  ...    0   0     0      1    0     0      0
1       0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
2       0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
3       0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
4       0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
...    ..  ...  ..  ..  ..  ..  ..  ...  ...  ..   ...    ...  ...   ...    ...
11309   0    0   0   0   0   0   0  ...    0   0     0      1    0     0      0
11310   0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
11311   0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
11312   0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0
11313   0    0   0   0   0   0   0  ...    0   0     0      0    0     0      0

[11314 rows x 1000 columns]

##拆解內容

In [ ]:
print(len(model.components_))

20

In [ ]:
print(model.transform(tf)) # 以主題呈現的文件
print(len(model.transform(tf)))

[[0.00208333 0.00208333 0.00208333 ... 0.3206343  0.00208333 0.00208333]
 [0.0025     0.0025     0.0025     ... 0.18793488 0.0025     0.0025    ]
 [0.00060241 0.01565983 0.00060241 ... 0.39589748 0.00060241 0.00060241]
 ...
 [0.00454545 0.00454545 0.00454545 ... 0.00454545 0.00454545 0.00454545]
 [0.00294118 0.00294118 0.00294118 ... 0.24767395 0.00294118 0.00294118]
 [0.00357143 0.00357143 0.00357143 ... 0.00357143 0.00357143 0.00357143]]
11314

In [ ]:
model.transform(tf)[0]

array([0.00208333, 0.00208333, 0.00208333, 0.00208333, 0.12551831,
       0.00208333, 0.00208333, 0.00208333, 0.00208333, 0.00208333,
       0.00208333, 0.00208333, 0.00208333, 0.51843072, 0.00208333,
       0.00208333, 0.00208333, 0.3206343 , 0.00208333, 0.00208333])

##補充 scikit-learn TFIDF


1.   詞頻（term frequency，TF）
2.   逆向檔案頻率（inverse document frequency，IDF）

目的：


*   找到文件當中的關鍵字，<font color=#FFFF00>怎樣的關鍵字是重要的？</font>	
  ><font color=#FFFF00>TF</font>	
  >
  >   出現最多次的字-><font color=#FF0000>不過因為每個文件的字數不同，無法比較</font>	
  >> 文件內的字數作為分母，將所有文件得到數值加以規範化。這也就是TF，特定單字在文件出現次數/文件總次數
  >
  ><font color=#FFFF00>IDF</font>
  >
  >定冠詞或是常用單字，得到很高的分數，<font color=#FF0000>a, an, the, and, or 等等</font>	
  >>1.先去除這些字詞(stopword)
  >>
  >>2.IDF會去計算一個字出現在文件的逆向頻率，這表示<font color=#FF0000>出現頻率越高</font>，出現在越多文件之中，但是<font color=#FF0000>得分會越低</font>

*  <font color=#FFFF00>TF和IDF相乘：TFxIDF，得到的綜合分數就是TFIDF。</font>

In [ ]:
#套件
from sklearn.feature_extraction.text import CountVectorizer
#「CountVectorizer」會計算單字出現在文件的次數；再透過「TfidfVectorizer」轉換成TFIDF和IDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
#直接使用「TfidfTransformer」計算TFID
import pandas as pd

###建立測試假文

In [ ]:
d1 = 'a b d e d f a f e fa d s a b n'
d2 = 'a z a f e fa h'
d3 = 'a z a f e fa h'

###計算：



*   <font color=#FF0000>vectorizer.get_feature_names()</font>	可以取得計算的單字
*   <font color=#FF0000>token_pattern</font>是<font color=#FF0000>(?u)\\b\\w\\w+\\b</font>，會過濾掉兩個字母以下的內容，但測試文本使用單個字母來測試，所以要加以改寫。將<font color=#FF0000>stop_word</font>設為<font color=#FF0000>None</font>也是同樣道理，比免去除單字，因為只是範例，而想看看所有結果：

####計算次數使用“<font color=#FF0000>CountVectorizer</font>”

補充：
[中英文操做](https://blog.csdn.net/weixin_38278334/article/details/82320307)

In [ ]:
vectorizer = CountVectorizer(stop_words=None, token_pattern="(?u)\\b\\w+\\b")  
X = vectorizer.fit_transform([d1,d2,d3])
r = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names(),index=['d1', 'd2', 'd3'])

print("CountVector")
r

CountVector

    a  b  d  e  f  fa  h  n  s  z
d1  3  2  3  2  2   1  0  1  1  0
d2  2  0  0  1  1   1  1  0  0  1
d3  2  0  0  1  1   1  1  0  0  1

####計算TFIDF使用“<font color=#FF0000>TfidfVectorizer</font>”

In [ ]:
vectorizer = TfidfVectorizer(sublinear_tf=False, stop_words=None, token_pattern="(?u)\\b\\w+\\b", smooth_idf=True)  
X = vectorizer.fit_transform([d1,d2,d3])
r = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names(), index=['d1', 'd2', 'd3'])
print("TFIDF")
r

TFIDF

           a         b         d  ...         n         s         z
d1  0.384107  0.433566  0.650349  ...  0.216783  0.216783  0.000000
d2  0.622686  0.000000  0.000000  ...  0.000000  0.000000  0.400911
d3  0.622686  0.000000  0.000000  ...  0.000000  0.000000  0.400911

[3 rows x 10 columns]

In [ ]:
print("IDF")
pd.DataFrame([vectorizer.idf_], columns=vectorizer.get_feature_names())

IDF

     a         b         d    e  ...         h         n         s         z
0  1.0  1.693147  1.693147  1.0  ...  1.287682  1.693147  1.693147  1.287682

[1 rows x 10 columns]

####計算TFIDF使用“<font color=#FF0000>TfidfTransformer</font>“

In [ ]:
transformer = TfidfTransformer(smooth_idf=True)
Z = transformer.fit_transform(X)
r = pd.DataFrame(Z.toarray(),columns=vectorizer.get_feature_names(), index=['d1', 'd2', 'd3'])
print("TFIDF")
r

TFIDF

           a         b         d  ...         n         s         z
d1  0.384107  0.433566  0.650349  ...  0.216783  0.216783  0.000000
d2  0.622686  0.000000  0.000000  ...  0.000000  0.000000  0.400911
d3  0.622686  0.000000  0.000000  ...  0.000000  0.000000  0.400911

[3 rows x 10 columns]

In [ ]:
print("IDF")
pd.DataFrame([transformer.idf_], columns=vectorizer.get_feature_names())

IDF

     a         b         d    e  ...         h         n         s         z
0  1.0  1.693147  1.693147  1.0  ...  1.287682  1.693147  1.693147  1.287682

[1 rows x 10 columns]